import { Geist, Geist_Mono } from "next/font/google";

import Image from 'next/image';

export const metadata = {
    title: "National Association of Dog Obedience Instructors",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <>
            <main>
                <section className="section-auth d-flex flex-column flex-lg-row">
                    <figure className="picture h-100">
                        <Image
                            src="/images/who-we-are-img.jpg"
                            alt="Eastern Regional Gathering"
                            width={1920}
                            height={1080}
                        />
                    </figure>
                    <div className='flex-fill d-flex h-100 overflow-auto'>
                        {children}
                    </div>
                </section>
            </main>
        </>
    );
}
