import Header from '../../components/Header';
import Footer from '../../components/Footer';

export const metadata = {
  title: "National Association of Dog Obedience Instructors",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Header />
      <main data-bs-header-fixed="true">
        {children}
      </main>
      <Footer />
    </>
  );
}
