import { AuthProvider } from "@/context/AuthContext";
import "./globals.scss";
import BackToTop from "@/components/common/BackToTop";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-bs-theme="light">
      <body>
        <AuthProvider>
          {children}
          {/* <BackToTop /> */}
        </AuthProvider>
      </body>
    </html>
  );
}
